version: '3.0'
services:
  backend:
    build: .
    container_name: datn_backend
    restart: unless-stopped
    command: "npm run start"
    volumes:
      - /var/log/mosquitto:/var/log/mosquitto
    ports:
      - 8181:8888
    env_file:
      - .env
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_COLLECTION=mosquitto
    networks:
      - datnet
    depends_on:
      - mongodb
    links: 
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: datn_mongodb
    restart: unless-stopped
    command: "mongod --auth --bind_ip_all"
    ports:
     - 27018:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin
     - MONGO_INITDB_DATABASE=test
    volumes:
      - /home/hius/datn/mongodb/data:/data/db
    networks:
      - datnet

networks:
  datnet:
    driver: bridge
