import * as dotenv from "dotenv";
dotenv.config();

const { PORT, SECRET_ACCESS_TOKEN, LOG_FILE_PATH, TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, 
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_COLLECTION} = process.env;

export { PORT, SECRET_ACCESS_TOKEN, LOG_FILE_PATH, TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, 
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_COLLECTION};